---
- name: "Install packages"
  retries: 3
  delay: 10
  until: output is success
  register: output
  ansible.builtin.package:
    update_cache: true
    name:
      - "git"

- name: "Install Lynis by clone the repository"
  retries: 3
  until: output is success
  ansible.builtin.git:
    repo: "https://github.com/CISOfy/lynis"
    dest: "{{ install_lynis__install_path }}"

- name: "Create a sym link to the bin"
  ansible.builtin.file:
    src: "{{ install_lynis__install_path }}/lynis"
    dest: "/bin/lynis"
    state: link
    owner: "root"
    group: "root"
    mode: "0700"

- name: "Send automatics report with cron"
  when: install_lynis__create_cron_job
  block:
    - name: "Install others packages"
      when: install_lynis__create_cron_job | default(false)
      retries: 3
      delay: 10
      until: output is success
      register: output
      ansible.builtin.package:
        update_cache: true
        name:
          - "cron"
          - "mailutils"
          - "colorized-logs"
          - "kbtin"

    - name: "Check if a cron file exist"
      register: cron_file
      ansible.builtin.stat:
        path: "/etc/cron.d/ansible_install_lynis__and_send_report"

    - name: "Configure automatic reports with cron"
      when: not cron_file.stat.exists
      ansible.builtin.cron:
        name: "ansible - send Lynis email reports"
        weekday: "{{ install_lynis__cron_job_weekday }}"
        minute: "{{ install_lynis__cron_job_minute }}"
        hour: "{{ install_lynis__cron_job_hour }}"
        user: "root"
        job: "lynis audit system --quick --pentest 2>&1  | ansi2html | mail -a 'MIME-Version: 1.0' -a 'Content-Type: text/html; charset=iso-8859-1' -s \"Lynis reports of $(hostname -f)\" {{ install_lynis__report_email_address }}"
        cron_file: "ansible_install_lynis__send_reports"
