---
- name: "Converge"
  hosts: "cicd-ubuntu-22"
  tasks:

    - name: "Include labocbz.install_lynis"
      tags:
        - "labocbz.install_lynis"
      vars:
        install_lynis__create_cron_job: "{{ inv_install_lynis__create_cron_job }}"
        install_lynis__cron_job_weekday: "{{ inv_install_lynis__create_cron_job }}"
        install_lynis__cron_job_minute: "{{ inv_install_lynis__cron_job_minute }}"
        install_lynis__cron_job_hour: "{{ inv_install_lynis__cron_job_hour }}"
        install_lynis__report_email_address: "{{ inv_install_lynis__create_cron_job }}"
        install_lynis__install_path: "{{ inv_install_lynis__install_path }}"
      ansible.builtin.include_role:
        name: "labocbz.install_lynis"
